theme:
  active: Gray # current playing song in list
  banner: LightGreen # the "spotify-tui" banner on launch
  error_border: Red # error dialog border
  error_text: LightRed # error message text (e.g. "Spotify API reported error 404")
  hint: LightGreen # hint text in errors
  hovered: "255, 255, 255" # hovered pane border
  inactive: Gray # borders of inactive panes
  playbar_background: Black # background of progress bar
  playbar_progress: "29, 185, 84" # filled-in part of the progress bar
  playbar_progress_text: White # song length and time played/left indicator in the progress bar
  playbar_text: "29, 185, 84" # artist name in player pane
  selected: "29, 185, 84" # a) selected pane border, b) hovered item in list, & c) track title in player
  text: "255, 255, 255" # text in panes
  header: "29, 255, 84" # header text in panes (e.g. 'Title', 'Artist', etc.)

keybindings:
  increase_volume: "="
behavior:
  seek_milliseconds: 5000
  tick_rate_milliseconds: 50
  # These icons require a patched nerd font.
  liked_icon: â™¥
  shuffle_icon: ğŸ”€
  repeat_track_icon: ğŸ”‚
  repeat_context_icon: ğŸ”
  playing_icon: â–¶
  paused_icon: â¸
  #Sets the window title to "spt - Spotify TUI" via ANSI escape code.
  set_window_title: true
